-- =============================================================
-- Creates the Products table and populates it with 100 records.
-- Run this script against the target SQL Server database once.
-- =============================================================

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Products')
BEGIN
    CREATE TABLE Products
    (
        Id          INT             IDENTITY(1,1) PRIMARY KEY,
        Name        NVARCHAR(255)   NOT NULL,
        Description NVARCHAR(MAX)   NULL,
        Price       DECIMAL(18,2)   NOT NULL,
        Category    NVARCHAR(100)   NULL
    );
END
GO

-- Seed 100 sample product records
INSERT INTO Products (Name, Description, Price, Category) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI settings', 29.99, 'Electronics'),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard with Cherry MX switches', 89.99, 'Electronics'),
('USB-C Hub', '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader', 45.50, 'Electronics'),
('Noise Cancelling Headphones', 'Over-ear headphones with active noise cancellation', 199.99, 'Electronics'),
('Webcam HD 1080p', 'Full HD webcam with built-in microphone and auto-focus', 59.99, 'Electronics'),
('Laptop Stand', 'Adjustable aluminum laptop stand for ergonomic posture', 35.00, 'Accessories'),
('Monitor Arm', 'Single monitor desk mount arm with full motion adjustment', 49.99, 'Accessories'),
('Desk Lamp LED', 'Dimmable LED desk lamp with USB charging port', 28.50, 'Lighting'),
('Bluetooth Speaker', 'Portable waterproof Bluetooth speaker with 12-hour battery', 39.99, 'Electronics'),
('External SSD 1TB', 'Portable solid state drive with USB 3.2 Gen 2 interface', 109.99, 'Storage'),
('HDMI Cable 6ft', 'High speed HDMI 2.1 cable supporting 4K at 120Hz', 12.99, 'Cables'),
('Wireless Charger', 'Qi-compatible fast wireless charging pad', 19.99, 'Electronics'),
('Power Strip Surge Protector', '6-outlet surge protector with USB ports', 24.99, 'Electrical'),
('Mousepad XL', 'Extended gaming mousepad with stitched edges', 15.99, 'Accessories'),
('Cable Management Kit', 'Desk cable organizer with clips and sleeves', 11.99, 'Accessories'),
('Portable Monitor 15.6 inch', 'Lightweight portable USB-C monitor for laptops', 179.99, 'Electronics'),
('Ethernet Cable Cat6 10ft', 'High speed Cat6 Ethernet cable for reliable networking', 8.99, 'Cables'),
('Webcam Cover', 'Sliding privacy cover for laptop webcams', 5.99, 'Accessories'),
('Screen Cleaning Kit', 'Microfiber cloth and spray solution for displays', 9.99, 'Accessories'),
('USB Flash Drive 64GB', 'High speed USB 3.0 flash drive with retractable design', 12.49, 'Storage'),
('Laptop Backpack', 'Water-resistant backpack with padded laptop compartment', 49.99, 'Bags'),
('Tablet Stand', 'Foldable aluminum stand for tablets and e-readers', 22.99, 'Accessories'),
('Smart Power Plug', 'Wi-Fi enabled smart plug with voice assistant support', 14.99, 'Smart Home'),
('Desk Organizer', 'Multi-compartment wooden desk organizer', 27.50, 'Office'),
('Whiteboard Markers Set', 'Pack of 12 dry-erase markers in assorted colors', 10.99, 'Office'),
('Wireless Presenter', 'Laser pointer and slide clicker with USB receiver', 24.99, 'Electronics'),
('Document Scanner', 'Compact portable document scanner with auto-feed', 149.99, 'Electronics'),
('Ink Cartridge Black', 'High yield black ink cartridge for office printers', 22.00, 'Office'),
('Photo Paper Glossy', 'Pack of 100 sheets glossy photo paper A4 size', 18.99, 'Office'),
('Label Maker', 'Handheld label maker with QWERTY keyboard', 39.99, 'Office'),
('Standing Desk Converter', 'Sit-stand desk converter with adjustable height', 189.99, 'Furniture'),
('Ergonomic Office Chair', 'Mesh back office chair with lumbar support', 249.99, 'Furniture'),
('Footrest Adjustable', 'Ergonomic under-desk footrest with tilt adjustment', 34.99, 'Furniture'),
('Desk Mat Leather', 'PU leather desk mat with waterproof surface', 19.99, 'Accessories'),
('Filing Cabinet 3 Drawer', 'Metal filing cabinet with lock and casters', 89.99, 'Furniture'),
('Bookshelf 5 Tier', 'Industrial style 5-tier bookshelf for office or home', 79.99, 'Furniture'),
('Corkboard Large', 'Wall-mounted cork bulletin board with aluminum frame', 29.99, 'Office'),
('Stapler Heavy Duty', 'Commercial stapler capable of stapling up to 100 sheets', 18.50, 'Office'),
('Paper Shredder', 'Cross-cut paper shredder with 8-sheet capacity', 59.99, 'Office'),
('Calculator Scientific', 'Advanced scientific calculator with 240 functions', 15.99, 'Office'),
('Wireless Earbuds', 'True wireless earbuds with charging case and touch controls', 79.99, 'Electronics'),
('Smart Watch', 'Fitness tracking smartwatch with heart rate monitor', 149.99, 'Electronics'),
('Action Camera 4K', 'Waterproof 4K action camera with image stabilization', 129.99, 'Electronics'),
('Drone Mini', 'Foldable mini drone with HD camera and GPS', 199.99, 'Electronics'),
('VR Headset', 'Virtual reality headset compatible with smartphones', 49.99, 'Electronics'),
('Gaming Controller', 'Wireless gaming controller with programmable buttons', 59.99, 'Gaming'),
('Gaming Mouse', 'High precision gaming mouse with 16000 DPI sensor', 69.99, 'Gaming'),
('Gaming Headset', 'Surround sound gaming headset with noise-cancelling mic', 89.99, 'Gaming'),
('Gaming Chair', 'Racing style gaming chair with adjustable armrests', 219.99, 'Gaming'),
('Gaming Desk', 'Carbon fiber surface gaming desk with cable management', 179.99, 'Gaming'),
('Microphone USB', 'Condenser USB microphone for podcasting and streaming', 69.99, 'Electronics'),
('Ring Light 10 inch', 'LED ring light with tripod stand for video calls', 29.99, 'Lighting'),
('Green Screen', 'Collapsible chroma key green screen background', 39.99, 'Accessories'),
('Tripod Camera', 'Lightweight aluminum tripod with quick release plate', 34.99, 'Accessories'),
('SD Card 128GB', 'High speed UHS-I SD card for cameras and devices', 19.99, 'Storage'),
('Network Switch 8 Port', 'Gigabit Ethernet unmanaged network switch', 24.99, 'Networking'),
('Wi-Fi Range Extender', 'Dual-band Wi-Fi extender with signal indicator', 29.99, 'Networking'),
('Router Mesh System', 'Whole home mesh Wi-Fi system covering up to 5000 sq ft', 199.99, 'Networking'),
('NAS Drive 2-Bay', 'Network attached storage enclosure for 2 hard drives', 159.99, 'Storage'),
('UPS Battery Backup', 'Uninterruptible power supply with 600VA capacity', 74.99, 'Electrical'),
('Thermal Paste', 'High performance thermal compound for CPU cooling', 7.99, 'Components'),
('RAM DDR4 16GB', '16GB DDR4 desktop memory module running at 3200MHz', 54.99, 'Components'),
('SSD NVMe 512GB', 'M.2 NVMe solid state drive with read speeds up to 3500MB/s', 64.99, 'Components'),
('Graphics Card Fan', 'Replacement GPU cooling fan set with dual fans', 19.99, 'Components'),
('CPU Cooler Tower', 'Air-cooled CPU tower cooler with 120mm fan', 44.99, 'Components'),
('Power Supply 650W', 'Semi-modular ATX power supply with 80 Plus Bronze rating', 69.99, 'Components'),
('Computer Case ATX', 'Mid-tower ATX case with tempered glass side panel', 79.99, 'Components'),
('Keyboard Wrist Rest', 'Memory foam keyboard wrist rest pad', 13.99, 'Accessories'),
('Privacy Screen Filter', 'Anti-glare privacy screen filter for 15.6 inch laptops', 29.99, 'Accessories'),
('Docking Station', 'Thunderbolt 4 docking station with dual display support', 189.99, 'Electronics'),
('Pen Tablet', 'Digital drawing tablet with pressure-sensitive pen', 59.99, 'Electronics'),
('Barcode Scanner', 'Handheld USB barcode scanner for inventory management', 39.99, 'Electronics'),
('Receipt Printer', 'Thermal receipt printer with USB and Ethernet ports', 129.99, 'Electronics'),
('Point of Sale Terminal', 'Touch screen POS terminal with card reader', 399.99, 'Electronics'),
('Smart Doorbell Camera', 'Video doorbell with motion detection and night vision', 89.99, 'Smart Home'),
('Smart Thermostat', 'Programmable Wi-Fi thermostat with energy saving features', 129.99, 'Smart Home'),
('Smart Light Bulb', 'Color changing smart LED bulb with app control', 12.99, 'Smart Home'),
('Smart Lock', 'Keyless entry smart lock with fingerprint scanner', 149.99, 'Smart Home'),
('Security Camera Indoor', 'Wi-Fi indoor security camera with two-way audio', 44.99, 'Smart Home'),
('Air Quality Monitor', 'Indoor air quality monitor with CO2 and humidity sensors', 79.99, 'Smart Home'),
('USB Microphone Arm', 'Adjustable boom arm for desk-mounted microphones', 24.99, 'Accessories'),
('Headphone Stand', 'Aluminum headphone stand with cable holder', 16.99, 'Accessories'),
('Anti-Fatigue Mat', 'Standing desk anti-fatigue comfort floor mat', 39.99, 'Furniture'),
('Monitor Light Bar', 'Screen mounted LED light bar for reduced eye strain', 49.99, 'Lighting'),
('Wireless Trackpad', 'Multi-touch wireless trackpad for desktop computers', 69.99, 'Electronics'),
('KVM Switch 2-Port', '2-port USB KVM switch for sharing peripherals', 29.99, 'Electronics'),
('Portable Projector', 'Mini LED projector with HDMI and Wi-Fi connectivity', 169.99, 'Electronics'),
('Digital Photo Frame', 'Wi-Fi digital photo frame with 10 inch display', 89.99, 'Electronics'),
('E-Reader 6 inch', 'E-ink display e-reader with front light and Wi-Fi', 119.99, 'Electronics'),
('Fitness Tracker Band', 'Slim fitness band with sleep tracking and notifications', 49.99, 'Electronics'),
('Portable Battery Pack', '20000mAh portable charger with fast charging support', 34.99, 'Electronics'),
('Car Phone Mount', 'Magnetic car phone holder for dashboard or air vent', 14.99, 'Accessories'),
('Keyboard Cleaning Gel', 'Reusable cleaning gel for keyboards and electronics', 6.99, 'Accessories'),
('HDMI to VGA Adapter', 'HDMI to VGA video adapter for legacy monitors', 9.99, 'Cables'),
('DisplayPort Cable 6ft', 'DisplayPort 1.4 cable supporting 8K resolution', 14.99, 'Cables'),
('Audio Splitter Cable', '3.5mm audio splitter for sharing headphone output', 4.99, 'Cables'),
('Surge Protector Tower', '12-outlet tower surge protector with USB-C ports', 34.99, 'Electrical'),
('Extension Cord 25ft', 'Heavy duty 3-prong extension cord for indoor and outdoor use', 19.99, 'Electrical'),
('Smart Plug Mini 2-Pack', 'Compact Wi-Fi smart plugs with scheduling and timers', 19.99, 'Smart Home');
GO